sudo: required

services:
- docker

language: c++

before_install:
- openssl aes-256-cbc -K $encrypted_93f1b6e3c30c_key -iv $encrypted_93f1b6e3c30c_iv
  -in proj.android-studio/app/src/debug/google-services.json.enc
  -out proj.android-studio/app/src/debug/google-services.json
  -d
- openssl aes-256-cbc -K $encrypted_bd1ec886c030_key -iv $encrypted_bd1ec886c030_iv
  -in scripts/debug.keystore.enc -out scripts/debug.keystore
  -d
- docker pull yjwong/playbook

script:
- echo "sdk.dir=/android-sdk" >> proj.android-studio/local.properties
- echo "ndk.dir=/android-ndk-r14" >> proj.android-studio/local.properties
- docker run -it
  -v $(pwd):/playbook
  -v $(pwd)/scripts/debug.keystore:/root/.android/debug.keystore
  -w /playbook/proj.android-studio yjwong/playbook
  ./gradlew --configure-on-demand --parallel assembleDebug

notifications:
  slack:
    secure: g9sX6BlGqpCFPGrL2wiNG1nKd3b26y90K59P/vCpPaie+ETPpIyrExfsVFg6iQFjnCxdQj7VufIoP+5rdMDdeGp6ODFnrs8zsQBaKV8+NKf5YXM1W8tDESOE0xPNBVPLV8e8RbxgKPEKh1A3WpqdIuakkF29JyXyd7jXZrO3kc9vWgX7EFU8RIf7KLEazvGknaPNGuaJ6LMpvpfJfaYqOcJmu6wcrWteQe+DBFgm6tZEeE8Clt0BiALSOoRIHthPFK5V/w8quEFnkop0lF6JrBTCE2YmBILSCeoMGTAk0Kgj5dq66msSQX/KtGNX/3KG+Xqafr7sUyRl+2jUxeKJTsLx/e3rpw3N1glgJ8co0wtAThYjvdmZ0QqurCrsAdEYVGkxo7jS3p0q3awqaE3YMZ3JrxbdfuZQfQCZl90XVrZHaV3PTkI8/Qj+MXQb9vDI6frMrQgGF6W1VPt7t8dLzc0ZTyatGKmRX2Kwl0AkHF4Al8AdVrFl7Ef4rXHagDVvh6OH8CrFLYD7wrOrkL5hmvMmrfQyN7VILPw6eBwS6auukfKrQTPvOslqmP1iL48nz5YtLCz/XeR08bTlRs5pk1qOxcTEmcpfHBEto3C7I2MdSTwbX3O2MVAHzGMK2sbpc0xk4pwu3Ve84kqA3zMx1Wfrph6T2cqttysbgzuwGCA=

addons:
  artifacts:
    s3_region: us-east-1
    paths:
      - proj.android-studio/app/build/outputs/apk/playbook-debug.apk
